# Generated by Django 4.2.8 on 2023-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guest_count',
            new_name='guest_number',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
